// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRKWgmgnuXB0Z8Q3NtySYB6omjzTHCW0',
    appId: '1:998692255191:web:3a0c461cf57000cb190792',
    messagingSenderId: '998692255191',
    projectId: 'travelvlog-cb8ca',
    authDomain: 'travelvlog-cb8ca.firebaseapp.com',
    storageBucket: 'travelvlog-cb8ca.appspot.com',
    measurementId: 'G-J076PQ6XGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMSAPv8AyVGnv9FJ6BaB70Anx-l1TO-g',
    appId: '1:998692255191:android:e2f842f5073f012e190792',
    messagingSenderId: '998692255191',
    projectId: 'travelvlog-cb8ca',
    storageBucket: 'travelvlog-cb8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoSOjKpoFTWPJ3GYzkbSShmvCirjjoV6A',
    appId: '1:998692255191:ios:27ad998212aababd190792',
    messagingSenderId: '998692255191',
    projectId: 'travelvlog-cb8ca',
    storageBucket: 'travelvlog-cb8ca.appspot.com',
    iosBundleId: 'com.alwaysbecreative.travelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoSOjKpoFTWPJ3GYzkbSShmvCirjjoV6A',
    appId: '1:998692255191:ios:06e5c1e8dde52f2b190792',
    messagingSenderId: '998692255191',
    projectId: 'travelvlog-cb8ca',
    storageBucket: 'travelvlog-cb8ca.appspot.com',
    iosBundleId: 'com.alwaysbecreative.travelBooking.RunnerTests',
  );
}
